### ISSUE TITLE
Firmware for flysky

### ISSUE THREAD

**Issue by infernos90** [meltoner/NEM_UAVRC_MEGA#1]
Hello, is it necesary to flash a specific firmware for flysky?
Is it posible to save a waypoints from transmitter?

**Comment by meltoner** [comment]
Hi we do not use a specific firmware for flysky. we use as from the factory.
you can save one way point from the transmitter.

**Comment by infernos90** [comment]
I know I'm annoying but I apologize.  I am excited about your project and would like to know if you can help me adapt it for a bait boat.  I would like to know if you can modify the arduino code so that you save 2-3 gps coordinates and when the boat gets there it executes a servo open command.  thank you and much respect.

**Comment by infernos90** [comment]
Something like this https://youtu.be/YnJC4XFGN8c

**Comment by meltoner** [comment]
Sure you can modify the code since it already includes how to reach one target. Interchanging the existing target with an array would be the key modification. how would you enter the gps coords? currently the logic is to get feadback from the gps so you know you have reached the target position and then you can open the bait.

**Comment by infernos90** [comment]
"how would you enter the gps coord?"
No. It is possible to save from transmitter? Exemple when i riched the specific point, switch button channel 8 to save it?

**Comment by meltoner** [comment]
Well that how its currently done. It first derives the starting point on boot up, but you can update home using the switch. 
Do you have some island you want to avoid and you need multiple ?

**Comment by infernos90** [comment]
For bait boat is necesary to save one home point and  few waypoints (2-3 is enough). Another question is if it possible to return the boat constantly without this pause for searching gps.

**Comment by meltoner** [comment]
inferno anything is possible. feel free to expand the code at your convenience

**Comment by infernos90** [comment]
first i need to learn c++... I am good only on soldering and building things... Thanks

**Comment by meltoner** [comment]
i see inferno, maybe in the future i wont have so many in my plate and i could do it for you, or you may soon be in a position to do it! talk again!

**Comment by infernos90** [comment]
Ok. Thanks. I subscribed you!

**Comment by oldcityboy** [comment]
> Yem botu için bir ev noktası ve birkaç rota noktası (2-3 yeterlidir) kaydetmek gerekir. Bir diğer soru ise gps araması için bu duraklama olmadan botu sürekli döndürmenin mümkün olup olmadığıdır.

Hello, have you installed GPS autopilot and location marking inside the feeding boat?

**Comment by meltoner** [comment]
have a read at the documentation
